site_name: swoole document
site_url: https://swooleo.github.io/docs/
nav:
- 介绍: index.md
- 快速开始: 快速开始.md
- Coroutine:
  - Coroutine:
    - Coroutine::set: coroutine/coroutine/set.md
    - Coroutine::create: coroutine/coroutine/create.md
    - Coroutine::defer: coroutine/coroutine/defer.md
    - Coroutine::exists: coroutine/coroutine/exists.md

theme:
  name: 'material'
