site_name: swoole document
site_url: https://swooleo.github.io/docs/
nav:
- 介绍: index.md
- 快速开始: 快速开始.md
- Coroutine:
  - Coroutine:
    - Coroutine::set: coroutine/coroutine/set.md
    - Coroutine::create: coroutine/coroutine/create.md
    - Coroutine::defer: coroutine/coroutine/defer.md
    - Coroutine::getCid: coroutine/coroutine/getCid.md
    - Coroutine::getPcid: coroutine/coroutine/getPcid.md
    - Coroutine::exists: coroutine/coroutine/exists.md
    - Coroutine::getContext: coroutine/coroutine/getContext.md
    - Coroutine::yield: coroutine/coroutine/yield.md
    - Coroutine::resume: coroutine/coroutine/resume.md
    - Coroutine::list: coroutine/coroutine/list.md
    - Coroutine::stats: coroutine/coroutine/stats.md
    - Coroutine::getBackTrace: coroutine/coroutine/getBackTrace.md
    - Coroutine::enableScheduler: coroutine/coroutine/enableScheduler.md
    - Coroutine::disableScheduler: coroutine/coroutine/disableScheduler.md
  - Channel:
    - Channel->__construct: coroutine/channel/__construct.md
    - Channel->push: coroutine/channel/push.md
    - Channel->pop: coroutine/channel/pop.md
    - Channel->stats: coroutine/channel/stats.md
    - Channel->close: coroutine/channel/close.md
    - Channel->length: coroutine/channel/length.md
    - Channel->isEmpty: coroutine/channel/isEmpty.md
    - Channel->isFull: coroutine/channel/isFull.md
    - Channel->capacity: coroutine/channel/capacity.md
    - Channel->errCode: coroutine/channel/errCode.md
  - Server:
    - Server->__construct: coroutine/server/__construct.md
    - Server->set: coroutine/server/set.md
    - Server->handle: coroutine/server/handle.md
    - Server->start: coroutine/server/start.md
    - Server->shutdown: coroutine/server/shutdown.md
  - Scheduler:
    - Scheduler->set: coroutine/scheduler/set.md
    - Scheduler->add: coroutine/scheduler/add.md
    - Scheduler->parallel: coroutine/scheduler/parallel.md
    - Scheduler->start: coroutine/scheduler/start.md
- Table:
  - Introduction: table/introduction.md
  - Table->__construct: table/__construct.md
  - Table->column: table/column.md
  - Table->create: table/create.md
  - Table->set: table/set.md
  - Table->incr: table/incr.md
  - Table->decr: table/decr.md
  - Table->exist: table/exist.md
  - Table->count: table/count.md
  - Table->del: table/del.md
  - Table->size: table/size.md
  - Table->memorySize: table/memorySize.md
    
theme:
  name: 'material'

markdown_extensions:
  - codehilite
