site_name: swoole document
site_url: https://swooleo.github.io/docs/
nav:
- 介绍: index.md
- 快速开始: 快速开始.md
- Coroutine:
  - Coroutine:
    - Scheduler::Set: coroutine/scheduler/set.md

theme:
  name: 'material'
