site_name: swoole document
site_url: https://swooleo.github.io/docs/
nav:
- 介绍: index.md
- 快速开始: 快速开始.md
- Coroutine:
  - Coroutine:
    - Coroutine::set: coroutine/coroutine/set.md
    - Coroutine::create: coroutine/coroutine/create.md
    - Coroutine::defer: coroutine/coroutine/defer.md
    - Coroutine::getCid: coroutine/coroutine/getCid.md
    - Coroutine::getPcid: coroutine/coroutine/getPcid.md
    - Coroutine::exists: coroutine/coroutine/exists.md
    - Coroutine::getContext: coroutine/coroutine/getContext.md
    - Coroutine::yield: coroutine/coroutine/yield.md
    - Coroutine::resume: coroutine/coroutine/resume.md
    - Coroutine::list: coroutine/coroutine/list.md
    - Coroutine::stats: coroutine/coroutine/stats.md
    - Coroutine::getBackTrace: coroutine/coroutine/getBackTrace.md
    - Coroutine::enableScheduler: coroutine/coroutine/enableScheduler.md

theme:
  name: 'material'
